title: "[question] <feature-name-goes-here>"
labels: ["question"]

body:
  - type: input
    attributes:
      label: Nombre del componente

  - type: textarea
    attributes:
      label: Descripción de la Solicitud
    validations:
      required: true    
  
  - type: input
    attributes:
      label: Ambiente
      placeholder: dev, qa, pdn

  - type: input
    attributes:
      label: Versión del aplicativo
      placeholder: v.1.0.o
  
  - type: textarea
    attributes:
      label: Contexto adicional
    validations:
      required: true

  - type: textarea
    attributes:
      label: Comportamiento esperado
    validations:
      required: true

  - type: input
    attributes:
      label: EVC
    validations:
      required: true

  - type: input
    attributes:
      label: Célula
    validations:
      required: true

  - type: input
    attributes:
      label: Nombre del solicitante
    validations:
      required: true

  - type: input
    attributes:
      label: Célula galatea
    validations:
      required: true

  - type: textarea
    attributes:
      label: Detalle respuesta
    validations:
      required: true

  - type: input
    attributes:
      label: Diagnóstico de Cierre
    validations:
      required: true

  - type: input
    attributes:
      label: Fecha de cierre
    validations:
      required: true

  - type: input
    attributes:
      label: Responsable
    validations:
      required: true

  - type: input
    attributes:
      label: Capa
    validations:
      required: true

  - type: input
    attributes:
      label: Task
    validations:
      required: true

  - type: textarea
    attributes:
      label: Datos adjuntos
    validations:
      required: true

      
