name: General Discussion
description: Start a new discussion topic
title: ''
labels: discussion
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        ## Topic
        Describe the main topic of your discussion.

  - type: textarea
    id: topic
    attributes:
      label: Topic
      description: Provide a clear and concise topic for the discussion.
      placeholder: "Enter the main topic of your discussion here"
      value: ""

  - type: markdown
    attributes:
      value: |
        ## Details
        Provide additional details or context about the topic. This can include background information, related issues, or relevant examples.

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Provide detailed information about the discussion topic.
      placeholder: "Enter additional details here"
      value: ""

  - type: markdown
    attributes:
      value: |
        ## Questions and Considerations
        - List any questions you have regarding the topic.
        - Add any considerations or points of discussion.

  - type: textarea
    id: questions
    attributes:
      label: Questions and Considerations
      description: List any questions or considerations related to the topic.
      placeholder: "Enter questions and considerations here"
      value: ""

  - type: markdown
    attributes:
      value: |
        ## Additional Context
        Add any other context or screenshots that might help others understand your discussion topic.

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Provide any other context or screenshots.
      placeholder: "Enter additional context here"
      value: ""
