body:
  - type: textarea
    attributes:
      label: Por favor, describa la asesoría que necesita
    validations:
      required: true   

  - type: input
    attributes:
      label: Nombre del equipo que reporta la asesoria      
    validations:
       required: true

