body:
  - type: textarea
    attributes:
      label: Iniciar una asesoria
    validations:
      required: true   

  - type: input
    attributes:
      label: Nombre del equipo
      description: Nombre del equipo que reporta la asesoria

