name: Mejora de documentación
description: Con la solicitud de mejora de documentación puede contribuir agregando o modificando documentación al componente.
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Descripción 
      description: >-
        Describa de manera clara y concisa la propuesta de actualización de documentación, explica por qué es necesaria esta actualizacion y que beneficios traera. 
        Puede adicionar capturas de pantalla.
