name: Reportar una vulnerabilidad de seguridad
description: Describa claramente el problema de seguridad encontrado
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: La vulnerabilidad de seguridad
      description: >-
        Detalle la vulnerabilidad de seguridad identificada, incluyendo su impacto potencial en el componente afectado. Además, si existe, describa la solución propuesta para mitigar esta vulnerabilidad.
        Puede adicionar capturas de pantalla.

  - type: markdown
    attributes:
      value: |
        ## Entorno de ejecución    

  - type: input
    validations:
      required: true
    attributes:
      label: Version del componente afectado
      placeholder: v1.0.0
