name: Reportar una vulnerabilidad de seguridad
description: Describa claramente el problema de seguridad encontrado
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: La vulnerabilidad de seguridad
      description: >-
        Explique el detalle de la vulnerabilidad de seguridad y el impacto que tendría en el componente.
        Puede adicionar capturas de pantalla.

  - type: markdown
    attributes:
      value: |
        ## Entorno de ejecución    

  - type: input
    validations:
      required: true
    attributes:
      label: Ambiente
      placeholder: dev, qa, pdn

  - type: input
    validations:
      required: true
    attributes:
      label: Version del aplicativo
      placeholder: v1.0.0

  - type: textarea
    attributes:
      label: Informacion adicional
      description: >
        Añada cualquier otra información relevante.
