name: Reportar una vulnerabilidad de seguridad
description: Describa claramente el problema de seguridad encontrado
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: La vulnerabilidad de seguridad
      description: >-
        Explique el detalle de la vulnerabilidad de seguridad, el impacto que tendría en el componente y, en caso de tener una solucion propuesta describela.
        Puede adicionar capturas de pantalla.

  - type: markdown
    attributes:
      value: |
        ## Entorno de ejecución    

  - type: input
    validations:
      required: true
    attributes:
      label: Version del componente afectado
      placeholder: v1.0.0
