name: Reportar una vulnerabilidad de seguridad
description: Describa claramente el problema de seguridad encontrado
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: La vulnerabilidad de seguridad
      description: >-
        Describa claramente el problema de seguridad encontrado.
        Puede adicionar capturas de pantalla.

  - type: textarea
    attributes:
      label: Pasos para reproducir
      description: Paso a paso para reproducir el problema
      value: |
        1. Ir a '...'
        2. Haga clic en '....'
        3. Despl치cese hacia abajo hasta '....'
        4. Ver problema de seguridad
        ...
    validations:
      required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: Impacto
      description: Describa el impacto potencial de este problema de seguridad

  - type: markdown
    attributes:
      value: |
        ## Entorno de ejecuci칩n    

  - type: input
    validations:
      required: true
    attributes:
      label: Ambiente
      placeholder: dev, qa, pdn

  - type: input
    validations:
      required: true
    attributes:
      label: Version del aplicativo
      placeholder: v1.0.0

  - type: textarea
    attributes:
      label: Informacion adicional
      description: >
        A침ada cualquier otra informaci칩n relevante.
