name: Reportar error
description: Reportar error
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describa el error
      description: >-
        Por favor describa claramente el error encontrado.
        Puede adicionar capturas de pantalla.

  - type: textarea
    id: repro
    attributes:
      label: Como replicar el error
      description: Paso a paso para reproducir el error
      value: |
        1. Ir a '...'
        2. Haga clic en '....'
        3. Despl치cese hacia abajo hasta '....'
        4. Ver error
        ...
    validations:
      required: true

  - type: input
    validations:
      required: true
    attributes:
      label: Comportamiento esperado
      description: Describa lo que esperaba que ocurriera.

  - type: markdown
    attributes:
      value: |
        ## Entorno de ejecuci칩n    

  - type: input
    validations:
      required: true
    attributes:
      label: Ambiente
      placeholder: dev, qa, pdn

  - type: input
    validations:
      required: true
    attributes:
      label: Version del aplicativo
      placeholder: v1.0.0

  - type: textarea
    attributes:
      label: Informacion adicional
      description: >
        A침ada cualquier otra informaci칩n relevante.
