name: Solicitud de mejora
description: La solicitud de mejora se emplea para formalizar y documentar propuestas que buscan mejorar características existentes o proponer nuevas funcionalidades.
title: prueba
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Nueva funcionalidad o actualización.
      description: >-
        Describa la nueva funcionalidad o actualización. Puede adicionar capturas de pantalla.

  - type: input
    attributes:
      label: Fecha aproximada de la mejora
      description: >-
        Indique la fecha aproximada de cuando requiere esta nueva implementación.

  - type: input
    validations:
      required: true
    attributes:
      label: Nombre de usuario del dueño de producto.       

  - type: textarea
    id: repro
    attributes:
      label: ¿Por qué la considera necesaria?
      description: Explique la razón por la cual considera necesaria esta nueva funcionalidad o actualización.
    validations:
      required: true
