name: Report an issue with Immich
description: Report an issue with Immich
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describa el error
      description: >-
        Por favor describa claramente el error encontrado.
        
  - type: textarea
    id: repro
    attributes:
      label: Como replicar el error
      description: Paso a paso para reproducir el error
      value: |
        1. Ir a '...'
        2. Haga clic en '....'
        3. Desplácese hacia abajo hasta '....'
        4. Ver error
        ...
      render: bash
    validations:
      required: true 

  - type: markdown
    attributes:
      value: |
        ## Environment

  - type: input
    validations:
      required: true
    attributes:
      label: The OS that Immich Server is running on
      placeholder: Ubuntu 22.10, Debian, Arch...etc

  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: Version of Immich Server
      placeholder: v1.0.0

  - type: input
    validations:
      required: true
    attributes:
      label: Version of Immich Mobile App
      placeholder: v1.0.0

  - type: checkboxes
    validations:
      required: true
    attributes:
      label: Platform with the issue
      options:
        - label: Server
        - label: Web
        - label: Mobile

  - type: textarea
    validations:
      required: true
    attributes:
      label: Your docker-compose.yml content
      render: YAML

  - type: textarea
    validations:
      required: true
    attributes:
      label: Your .env content
      description: Please provide the redacted .env content of your setup
      render: Shell

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant logs below. (code formatting is
        enabled, no need for backticks)
      render: shell
    validations:
      required: false
      
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.

  - type: markdown
    attributes:
      value: Thank you for submitting the form
