name: Solicitud de mejora
description: La solicitud de mejora se emplea para formalizar y documentar propuestas que buscan mejorar características existentes o proponer nuevas funcionalidades.
title: prueba
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Nueva funcionalidad o actualización.
      description: >-
        Describa la nueva funcionalidad o actualización. Puede adicionar capturas de pantalla.

  - type: textarea
    id: repro
    attributes:
      label: ¿Por qué la considera necesaria?
      description: Explique la razón por la cual considera necesaria esta nueva funcionalidad o actualización.
    validations:
      required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: Impacto esperado
      description: Describa cómo esta funcionalidad o actualizacion beneficiará a los usuarios.
